# Generated by Django 3.0.7 on 2020-07-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200630_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
