# Generated by Django 3.0.7 on 2020-07-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_purchase_is_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='is_returned',
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'NEW'), (2, 'REVIEW'), (3, 'REJECTED'), (4, 'APPROVED')],),
            preserve_default=False,
        ),
    ]
